### ISSUE TITLE
Getting zero optimized pages

### ISSUE THREAD

**Issue by felix2056** [MacroMan/nitropack-api#2]
I deployed to live but Nitropack isn't connecting to my website and I get zero optimized pages. Although the purgeCache method fires successfully.

Here's the error message:
`No results available. Either NitroPack.io is not fully installed on your site, or our service was not able to optimize your home page in a reasonable time frame.`

![screenshot-nitropack io-2021 07 31-08_34_12](https://user-images.githubusercontent.com/42879067/127732651-5515e7cd-2d0b-4bff-a396-7fef89119407.png)

Can you please share more details on how to use the package properly?
Thanks

**Comment by MacroMan** [comment]
This package is an unofficial implementation of https://nitropack.io/download/plugin/nitropack-php-sdk-limited-support to enable installation via composer. 

I am unable to offer any support with nitropack itself.
